{
  "uuid": "e92b0212-9919-43d8-8fd2-2d716ee003f9",
  "historyId": "024264f9e89d71e4d9fc5f5c1ae5dd3e",
  "testCaseId": "82dcddb90948ae59fcb4a4b3109996e5",
  "fullName": "Contatos.Application.Test:Contatos.Application.Test.UseCases.AtualizaContatoUseCaseTest.ExecuteAsync_ContatoValido_DeveAtualizarContatoComSucesso()",
  "labels": [
    {
      "name": "thread",
      "value": ".NET Long Running Task"
    },
    {
      "name": "host",
      "value": "BRO-NT"
    },
    {
      "name": "language",
      "value": "C#"
    },
    {
      "name": "framework",
      "value": "xUnit.net"
    },
    {
      "name": "testClass",
      "value": "Contatos.Application.Test.UseCases.AtualizaContatoUseCaseTest"
    },
    {
      "name": "testMethod",
      "value": "Atualizar contato com valores válidos deve atualizar com sucesso"
    },
    {
      "name": "package",
      "value": "Contatos.Application.Test.UseCases.AtualizaContatoUseCaseTest"
    }
  ],
  "links": [],
  "name": "Atualizar contato com valores válidos deve atualizar com sucesso",
  "status": "failed",
  "statusDetails": {
    "known": false,
    "muted": false,
    "flaky": false,
    "message": "Expected result.IsSuccess to be true because o contato deve ser atualizado, but found False.",
    "trace": "   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)\r\n   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)\r\n   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)\r\n   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)\r\n   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)\r\n   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)\r\n   at FluentAssertions.Primitives.BooleanAssertions`1.BeTrue(String because, Object[] becauseArgs)\r\n   at Contatos.Application.Test.UseCases.AtualizaContatoUseCaseTest.ExecuteAsync_ContatoValido_DeveAtualizarContatoComSucesso() in C:\\dev\\fiap-net\\fiap.5nett.contatos\\test\\Contatos.Application.Test\\UseCases\\AtualizaContatoUseCaseTest.cs:line 37\r\n   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 276\r\n--- End of stack trace from previous location ---\r\n   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48\r\n   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90"
  },
  "stage": "finished",
  "steps": [],
  "attachments": [],
  "parameters": [],
  "start": 1727376728320,
  "stop": 1727376728616
}