{
  "uuid": "f470d0e3-c4c7-44da-af6a-abcdb9dc5d60",
  "historyId": "f5edd734f49c1b07f356ea0b881ab6fb",
  "testCaseId": "e59037914cf64c65da9788a48ca6e9e0",
  "fullName": "Contatos.Application.Test:Contatos.Application.Test.UseCases.AtualizarContatoUseCaseTest.ExecuteAsync_ContatoValido_DeveAtualizarContatoComSucesso()",
  "labels": [
    {
      "name": "thread",
      "value": ".NET Long Running Task"
    },
    {
      "name": "host",
      "value": "BRO-NT"
    },
    {
      "name": "language",
      "value": "C#"
    },
    {
      "name": "framework",
      "value": "xUnit.net"
    },
    {
      "name": "testClass",
      "value": "Contatos.Application.Test.UseCases.AtualizarContatoUseCaseTest"
    },
    {
      "name": "testMethod",
      "value": "Atualizar contato com valores válidos deve atualizar com sucesso"
    },
    {
      "name": "package",
      "value": "Contatos.Application.Test.UseCases.AtualizarContatoUseCaseTest"
    }
  ],
  "links": [],
  "name": "Atualizar contato com valores válidos deve atualizar com sucesso",
  "status": "failed",
  "statusDetails": {
    "known": false,
    "muted": false,
    "flaky": false,
    "message": "Expected contato to be <null> because não pode ser nulo, but found 3ebed4e3-e4e5-45c0-b58c-8bfb5177ee74.",
    "trace": "   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)\r\n   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)\r\n   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)\r\n   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)\r\n   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)\r\n   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)\r\n   at FluentAssertions.Primitives.ReferenceTypeAssertions`2.BeNull(String because, Object[] becauseArgs)\r\n   at Contatos.Application.Test.UseCases.AtualizarContatoUseCaseTest.ExecuteAsync_ContatoValido_DeveAtualizarContatoComSucesso() in C:\\dev\\fiap-net\\fiap.5nett.contatos\\test\\Contatos.Application.Test\\UseCases\\AtualizarContatoUseCaseTest.cs:line 38\r\n   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 276\r\n--- End of stack trace from previous location ---\r\n   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48\r\n   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90"
  },
  "stage": "finished",
  "steps": [],
  "attachments": [],
  "parameters": [],
  "start": 1727381691363,
  "stop": 1727381691517
}